spring.application.name=Lab8
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WebShop;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Ghi pass của mình vào nha
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# cấu hình JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

# Mail config ghi gmail và password app chứ ko phải password gmail nha tạo rồi ghi vào
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nghiatttv00104@fpt.edu.vn
spring.mail.password=tzbn empm nksr lrif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# cấu hình Thymeleaf (tùy chọn, thường Spring Boot tự nhận)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html